#words for hangman game
# This file contains a list of words that can be used in the hangman game.

words=("lion", "tiger", "elephant", "giraffe", "zebra", "monkey", "kangaroo", "panda", "hippopotamus", "rhinoceros", 
            "crocodile", "alligator", "cheetah", "leopard", "hyena", "gorilla", "chimpanzee", "orangutan", "koala", "sloth",
            "dolphin", "whale", "shark", "octopus", "squid", "jellyfish", "starfish", "crab", "lobster", "shrimp",
            "seahorse", "turtle", "penguin", "seal", "otter", "beaver", "badger", "fox", "wolf", "bear", "moose", "elk",
            "seal", "otter", "beaver", "badger", "fox", "wolf", "bear", "moose", "elk", "deer",
            "rabbit", "squirrel", "chipmunk", "rat", "mouse", "bat", "hedgehog", "porcupine", "skunk", "opossum",
            "armadillo", "raccoon", "weasel", "ferret", "mink", "otter", "badger", "wolverine", "lynx", "bobcat",
            "cougar", "mountain lion", "jaguar", "leopard", "cheetah", "puma", "caracal", "serval", "ocelot", "margay", "jaguarundi",
            "fossa", "quoll", "tasmanian devil", "thylac            ine", "dingo", "wild dog", "coyote", "jackal",
            "hyena", "aardwolf", "meerkat", "mongoose", "mongos", "civet", "genet", "fossa", "binturong", "kinkajou",
            "coati", "ringtail", "cacomistle", "cuscus", "bandicoot", "bilby", "quokka", "quoll", "tasmanian tiger",
            "numbat", "wombat", "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot",
            "bilby", "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat", "wombat",
            "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby", "dunnart",
            "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat", "wombat", "koala", "kangaroo",
            "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby", "dunnart", "antechinus", "phascogale",
            "tasmanian devil", "thylacine", "numbat", "wombat", "koala", "kangaroo", "wallaby", "pademelon",
            "quokka", "potoroo", "bandicoot", "bilby", "dunnart", "antechinus", "phascogale", "tasmanian devil",
            "thylacine", "numbat", "wombat", "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo",
            "bandicoot", "bilby", "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat",
            "wombat", "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby",
            "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat", "wombat",
            "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby",
            "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat",
            "wombat", "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby",
            "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat", "wombat",
            "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby",
            "dunnart", "antechinus", "phascogale", "tasmanian devil", "thylacine", "numbat",
            "wombat", "koala", "kangaroo", "wallaby", "pademelon", "quokka", "potoroo", "bandicoot", "bilby",
            "dunnart", "antechinus", "phascogale")
word=list(words)
